In [ ]:
from sklearn.datasets import load_digits

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = load_digits()

In [ ]:
print(data.DESCR)

In [ ]:
features = data.data
target = data.target
data.target
features.shape,target.shape

((1797, 64), (1797,))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, target, train_size = 0.6, random_state = 3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1078, 64)
(719, 64)
(1078,)
(719,)


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
my_model = LogisticRegression()

In [ ]:
my_model.fit(X_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [ ]:
preds = my_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
print(accuracy_score(y_test, preds))

0.9582753824756607


In [ ]:
print(confusion_matrix(y_test, preds))6r5r5656

[[74  0  0  0  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  2  1]
 [ 0  1 77  0  0  0  0  0  0  0]
 [ 0  0  2 66  0  0  0  0  1  0]
 [ 0  4  0  0 79  0  1  1  1  0]
 [ 0  1  0  0  1 60  0  0  0  2]
 [ 0  1  0  0  0  1 55  0  1  0]
 [ 0  0  0  1  0  0  0 73  2  0]
 [ 0  1  0  0  0  1  0  0 66  0]
 [ 0  0  0  0  1  1  0  0  1 67]]


In [ ]:
from sklearn.decomposition import PCA

Initially I have 64 dimensions. Now I want to bring it down to 4 dimensions

In [ ]:
pca = PCA(n_components=15)

In [ ]:
pca.fit(X_train)

PCA(n_components=15)

In [ ]:
pca.components_

In [ ]:
pca.explained_variance_ratio_

array([0.14924092, 0.13473079, 0.1156578 , 0.08302537, 0.06011605,
       0.05032773, 0.04284684, 0.03556854, 0.03294893, 0.03039432,
       0.02454543, 0.02311797, 0.01912225, 0.01765655, 0.01482858])

In [ ]:
X_train_transformed = pca.transform(X_train)
X_test_transformed = pca.transform(X_test)

In [ ]:
X_train_transformed.shape, X_test_transformed.shape

((1078, 15), (719, 15))

In [ ]:
X_train_transformed

In [ ]:
pca.inverse_transform(X_train_transformed).shape

(1078, 64)

In [ ]:
my_model.fit(X_train_transformed,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [ ]:
preds = my_model.predict(X_test_transformed)

In [ ]:
print(accuracy_score(y_test, preds))

0.9443671766342142


In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
data = load_breast_cancer()
print(data.DESCR)